# Configuration for cargo-deny - updated to modern format
# See https://embarkstudios.github.io/cargo-deny/checks/cfg.html for full configuration

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause", 
    "0BSD",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "Unlicense",
    "MPL-2.0",
    "Zlib",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
]

# Confidence threshold for license detection
confidence-threshold = 0.8

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate marked as 'deny' is detected
deny = []
# Skip certain crates when checking for duplicates
skip = []
# Similarly named crates that are allowed to coexist
allow = []

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# A list of advisory IDs to ignore
ignore = []

[sources]
# Lint level for what to happen when a crate from a crate registry that is not in the allow list is detected
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not in the allow list is detected
unknown-git = "warn"
# List of allowed crate registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of allowed Git repositories
allow-git = []