version: '3.8'

services:
  # Redis for distributed registry and job queues
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - riglr-test

  # PostgreSQL for indexer
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: riglr_test
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: riglr_indexer_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U riglr_test"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - riglr-test

  # Neo4j for graph memory
  neo4j:
    image: neo4j:5-community
    environment:
      NEO4J_AUTH: neo4j/test_password
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_memory_heap_initial__size: "512M"
      NEO4J_dbms_memory_heap_max__size: "1G"
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - riglr-test

  # Mock API server for testing external web APIs
  wiremock:
    image: wiremock/wiremock:3.5.4
    ports:
      - "8080:8080"
    volumes:
      - ./test/wiremock/mappings:/home/wiremock/mappings
      - ./test/wiremock/__files:/home/wiremock/__files
    command: --verbose --global-response-templating
    networks:
      - riglr-test

networks:
  riglr-test:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  neo4j_data:
  neo4j_logs: