[package]
name = "riglr-evm-tools"
version.workspace = true
edition = "2021"
authors = ["Riglr Contributors"]
license = "MIT OR Apache-2.0"
description = "EVM blockchain tools for the Riglr framework"
repository = "https://github.com/riglr/riglr"
keywords = ["evm", "ethereum", "blockchain", "web3", "tools"]
categories = ["cryptography::cryptocurrencies", "api-bindings"]

[dependencies]
# Core dependencies
riglr-config = { workspace = true  }
riglr-core = { workspace = true  }
riglr-evm-common = { workspace = true  }
riglr-macros = { workspace = true  }
rig-core = { workspace = true }

# Async runtime
tokio = { workspace = true }
async-trait = { workspace = true }

# Ethereum/EVM
alloy = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }

# HTTP client
reqwest = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
tracing-subscriber = { workspace = true }
testcontainers = "0.24.0"

[features]
integration-tests = []
