[package]
name = "riglr-evm-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "A suite of rig-compatible tools for interacting with EVM-based blockchains"
readme = "README.md"
keywords = ["ethereum", "evm", "ai", "agent", "blockchain", "rig"]
categories = ["cryptography::cryptocurrencies", "web-programming::api-bindings"]
documentation = "https://docs.rs/riglr-evm-tools"

[dependencies]
# Core riglr and rig dependencies
rig-core = { workspace = true }
riglr-core = { workspace = true }
riglr-config = { workspace = true }
riglr-macros = { workspace = true }

# Async and Error Handling
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }

# Serialization and Schema
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }

# EVM Dependencies (using alloy-rs)
alloy = { workspace = true }
hex = "0.4"

# HTTP client
reqwest = { workspace = true }

# Utility
uuid = { workspace = true }

# Logging
tracing = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
tracing-subscriber = { workspace = true }
mockito = "1.0"
criterion = { workspace = true }
riglr-showcase = { path = "../riglr-showcase" }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
futures = "0.3"

# Removed workspace definition to be part of parent workspace

[[bench]]
name = "evm_benchmarks"
harness = false