[template]
cargo_generate_version = ">=0.20.0"

[placeholders.project-name]
type = "string"
prompt = "What is the name of your riglr project?"
regex = "^[a-zA-Z][a-zA-Z0-9_-]*$"

[placeholders.agent-name]
type = "string"
prompt = "What should your AI agent be called?"
default = "{{ project-name | kebab_case | title_case }}"

[placeholders.author-name]
type = "string"
prompt = "What is your name?"
default = "Anonymous"

[placeholders.author-email]
type = "string"
prompt = "What is your email address?"
default = "user@example.com"

[placeholders.blockchain-selection]
type = "string"
prompt = "Which blockchain(s) do you want to support?"
choices = ["solana-only", "ethereum-only", "multi-chain-basic", "multi-chain-advanced"]
default = "solana-only"

[placeholders.tool-bundle]
type = "string"
prompt = "Which tool bundle would you like?"
choices = ["minimal", "defi-focused", "analytics-focused", "cross-chain", "complete"]
default = "defi-focused"

[placeholders.include-solana-tools]
type = "bool"
prompt = "Include Solana tools (Jupiter, Pump.fun, etc.)?"
default = true

[placeholders.include-evm-tools]
type = "bool"
prompt = "Include EVM tools (Uniswap, 1inch, etc.)?"
default = false

[placeholders.include-web-tools]
type = "bool"
prompt = "Include web data tools (Twitter, DexScreener, news)?"
default = true

[placeholders.include-graph-memory]
type = "bool"
prompt = "Include graph memory for RAG capabilities?"
default = false

[placeholders.include-cross-chain-tools]
type = "bool"
prompt = "Include cross-chain bridge tools?"
default = false

[placeholders.include-hyperliquid-tools]
type = "bool"
prompt = "Include Hyperliquid derivatives tools?"
default = false

[placeholders.include-server]
type = "bool"
prompt = "Include HTTP server for API endpoints?"
default = false

[placeholders.agent-type]
type = "string"
prompt = "What type of agent are you building?"
choices = ["trading-bot", "market-analyst", "dex-arbitrage", "news-monitor", "portfolio-tracker", "custom"]
default = "trading-bot"

[placeholders.description]
type = "string"
prompt = "Brief description of your project:"
default = "A powerful on-chain AI agent built with riglr"

[conditional.'primary-chain == "solana"'.placeholders.solana-rpc-url]
type = "string"
prompt = "Solana RPC endpoint URL:"
default = "https://api.mainnet-beta.solana.com"

[conditional.'primary-chain == "ethereum" || primary-chain == "both"'.placeholders.ethereum-rpc-url]
type = "string"
prompt = "Ethereum RPC endpoint URL:"
default = "https://eth-mainnet.g.alchemy.com/v2/your-api-key"

[hooks]
pre = ["pre-script.rhai"]
post = ["post-script.rhai"]

[ignore]
# Files/directories to exclude from the template
exclude = [
    "target/",
    ".git/",
    "Cargo.lock",
    "pre-script.rhai",
    "post-script.rhai"
]