[book]
title = "riglr Documentation"
authors = ["riglr project contributors"]
description = "The official documentation for riglr, a production-ready blockchain-enabled AI agent framework."
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
theme = "theme"
git-repository-url = "https://github.com/riglr/riglr"
edit-url-template = "https://github.com/riglr/riglr/edit/main/docs/{path}"
# site-url = "/docs/"
additional-css = [
	"src/css/riglr.css",
]

[output.html.search]
limit-results = 20
use-boolean-search = true
boost-title = 2
boost-hierarchy = 1